### PR TITLE
Add GA Support for Submit and update service

### LINKED ISSUE #519: Add Google Analytics
**Overview** 
Google Analytics will allow us to gather quantitative measurements of user behaviour that we cannot access through logs or SmartLook. 

This is motivated by: 
* OKRs requiring us to measure traffic
* Analytics data could feed into user research  

@MJFaucherFolie has [detailed SmartLook's limitations here](https://docs.google.com/document/d/10Z8tMsEF4VtZDuD0t65jPFKJbYdDe25xhbGFWFvnK_Y/edit?usp=sharing)

**Tech approach** 
There is already a cookie acceptance bar on planning.data.gov.uk. 

**Acceptance Criteria** 
* Google Analytics is tracking users who accept cookies
* Google Analytics is not tracking users who reject cookies

### PR DESCRIPTION
**Pull request by DilwoarH**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Add GA Support for Submit and update service. This allows us to track user behaviour.

## Related Tickets & Documents

- Closes #519 

## QA Instructions, Screenshots, Recordings

_Please replace this line with instructions on how to test your changes, a note
on the devices and browsers this has been tested on, as well as any relevant
images for UI changes._

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Release Notes

- **New Features**
  - Integrated Google Analytics tracking capabilities into the application.
  - Updated cookie policy to reflect the use of Google Analytics cookies.

- **Documentation**
  - Enhanced README with details on Google Analytics integration and setup instructions.
  
- **Bug Fixes**
  - Corrected minor formatting issues in various files for improved readability.

- **Tests**
  - Added new test cases to ensure proper integration of Google Analytics scripts in the application layout and functionality.

### CODE REVIEW

**Review by rosado — CHANGES_REQUESTED** [review]
Looks good, but can you also update 
- the config schema in `config/util.js` with an optional GA entry? It's a decent form of documentation
- add item to the list in README under [API Keys/Secrets](https://github.com/digital-land/submit/#api-keyssecrets)

**Comment by DilwoarH** [comment]
> Looks good, but can you also update
> 
> * the config schema in `config/util.js` with an optional GA entry? It's a decent form of documentation
> * add item to the list in README under [API Keys/Secrets](https://github.com/digital-land/submit/#api-keyssecrets)

Done

**Review by rosado — DISMISSED** [review]

**Comment by stevenjmesser** [comment]
Will there be an associated cookie banner and update to the cookie & privacy notice? (Apologies if that’s on another issue but important they’re released at the same time.)

**Comment by DilwoarH** [comment]
> Will there be an associated cookie banner and update to the cookie & privacy notice? (Apologies if that’s on another issue but important they’re released at the same time.)

Hi Steve - Yes, we have been talking about the content for this and the things we need to add in.

Will keep you posted and only merge this once we have the banner up first.

**Comment by DilwoarH** [comment]
This is blocked until we have the cookie banner in

**Review by GeorgeGoodall-GovUk — DISMISSED** [review]

**Review by GeorgeGoodall-GovUk — APPROVED** [review]

**Pull request merged**
