### PR TITLE
check tool: update 'errors' page design & content

### PR DESCRIPTION
**Pull request by rosado**
## What type of PR is this? 

- [x] Feature

## Description

Update content & design elements of the check tool's "you've got errors" page.

## Related Tickets & Documents

- Issue #571 
- Followup to #610 

## QA Instructions, Screenshots, Recordings

For cases where the LPA name is not available (e.g. we have not arrived via deep link) the text at the bottom defaults to "How to improve the data".

image

But when the accessing the check tool via a deep link we can see the LPA's name:

image

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [x] Yes

## Release Notes

- **New Features**
  - Enhanced error summary presentation with a structured format, improving clarity for users.
  - Updated button text from "Upload a new version" to "Check your data" to better reflect functionality.
  - Introduced guidance for users on improving data quality with actionable steps.
  - Added a back navigation option on the status page for improved user experience.
  - Implemented functionality to track the last page visited by users.
  - Added a new back link on the confirmation page for easier navigation.
  - Streamlined map display in the no-errors template for clearer information presentation.
  - Improved readability of dataset names in the dataset banner.

- **Bug Fixes**
  - Improved error message handling to ensure accurate display and processing of error summaries.

- **Documentation**
  - Added JSDoc comments for methods to clarify functionality and expected outputs.

- **Tests**
  - Refined test cases to validate the new error summary structure and ensure robust error handling.
  - Updated tests to reflect changes in error handling and template structure.

### CODE REVIEW

**Comment by alextea** [comment]
The error summary table should use the error messages from this file: https://github.com/digital-land/submit/blob/main/src/content/fieldIssueMessages.csv

Can we any numerical or date columns use the `govuk-table__cell--numeric` class (George implemented this on the dataset table view)

**Comment by rosado** [comment]
> The error summary table should use the error messages from this file: https://github.com/digital-land/submit/blob/main/src/content/fieldIssueMessages.csv
> 

Those messages come from external service in the form of those strings. We can't look them up in the mentioned table.

**Comment by rosado** [comment]
@alextea I added the mentioned class to '-date' columns (in `<colgroup>`)

**Comment by DilwoarH** [comment]
Code looks good

@alextea - are you happy with the implementation?

**Comment by alextea** [comment]
Some issues still to fix:

- Back link missing from async processing pages, error results page, success results page and confirmation page
- Map missing from error results page
- Map missing from success results page
- Return link on confirmation page should be in human readable format ("Conservation area" rather than "conservation-area")

**Comment by rosado** [comment]
- [x] Back link missing from async processing pages, error results page, success results page and confirmation page
- [x] Return link on confirmation page should be in human readable format ("Conservation area" rather than "conservation-area")

As for the maps: 
- I can see the map when using this [article-4-direction-areas dataset URL](https://github.com/digital-land/submit/raw/refs/heads/main/test/datafiles/article4directionareas-ok.csv)
- when there are errors: maybe the data you used had geometry errors?

**Review by DilwoarH — COMMENTED** [review]
Code looks good - have design and product signed off?

**Pull request merged**
