### PR TITLE
add dataset action section

### LINKED ISSUE #617: Dataset details page: Dataset actions section
## Context:

- When an LPA has live data on the platform, they are no longer able to access the page that guides them through the process of checking and submitting their data, and so can't access the guidance or the check tool easily.
- There are several scenarios where they need to be able to do this.

## Acceptance criteria:

- As a data provider, when I'm on the dataset details page, I see a section next to the dataset details that lists out the possible actions, deep linking to the check tool, and linking to the relevant page of the guidance.

## Designs:

Image

### PR DESCRIPTION
**Pull request by DilwoarH**
## What type of PR is this? (check all applicable)

- Feature

## Description

Add dataset action section on dataset overview page

## Related Tickets & Documents

- Ticket Link
- Related Issue #
- Closes #617 

## QA Instructions, Screenshots, Recordings

localhost_5000_organisations_local-authority_BNE_brownfield-land_overview(iPad Pro)

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [x] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Release Notes

- **New Features**
	- Introduced a "Dataset actions" section on the dataset overview page, providing links for checking datasets and accessing guidance.
	- Enhanced dataset configuration structure for clearer access to guidance URLs.
	- Added a new function to retrieve guidance URLs for datasets, improving template capabilities.

- **Bug Fixes**
	- Updated dataset filtering logic to align with the new configuration structure.

- **Tests**
	- Added test cases for the new `getDatasetGuidanceUrl` function and the dataset actions section rendering.

### CODE REVIEW

**Review by rosado — CHANGES_REQUESTED** [review]
Please update `ConfigSchema` in config/util.js.

**Comment by DilwoarH** [comment]
> Please update `ConfigSchema` in config/util.js. 

Thanks will do, is there a reason why it doesn't cause the tests to fail?

**Comment by rosado** [comment]
> Thanks will do, is there a reason why it doesn't cause the tests to fail?

That schema is permissive (in contrast to our template schemas, which use `strictObject`).

**Review by rosado — APPROVED** [review]

**Comment by DilwoarH** [comment]
> Please update `ConfigSchema` in config/util.js.

Hey - done, I also added a missing one

**Review by GeorgeGoodall-GovUk — APPROVED** [review]
looks good!

**Pull request merged**
