### PR TITLE
segment datasets into mandated and ODP on org overview page

### LINKED ISSUE #618: Dashboard: Segment datasets into mandated and ODP
## Context:

- Depending on whether or not an LPA is part of the ODP programme, they will be required to provide different datasets.
- All LPAs are legally mandated to supply two datasets (brownfield land and developer contributions), and those that are part of the ODP programme are required to supply four additional datasets (article 4, conservation area, listed building, tree preservation orders).
- Given that we are now encouraging non-ODP LPAs to use the service to submit their brownfield land, we want to make it clear to them which datasets they are required to provide, and which they can provide.
- We should also be ensuring that the list this page shows is dynamic rather than hard-coded, and is using the [provisions table](https://datasette.planning.data.gov.uk/digital-land/provision?_sort=rowid&organisation__exact=local-authority%3ACMD) to generate this list.
- However, using this list would mean integrating a new specification into the service (Developer contributions), which we're not set up to do yet. The proposed interim solution would be to manually hide this for now, through a list of datasets which the service supports.

## Acceptance criteria:

- As a data provider, when I'm viewing the dashboard, it is clear to me which datasets are required through legislation, and which are part of the ODP programme.

## Designs:

image

### PR DESCRIPTION
**Pull request by rosado**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description

The datasets on organisations' overview pages are now grouped into two groups:
- mandatory datasets
- datasets covered by ODP

Where a particular dataset falls is done by looking up values in the `provision` table. 

### Summary of changes

- Changed the `OrgOverviewPage` schema `datasets` property to be a an object with (potentially) two fields, one for each group we currently support: `statutory` and `other`.
- fetch data from the `provision` table to group datasets
- updated the `organisations/overview` template, datasets are now grouped under two different headings (as in design)
	- extracted the list item into a macro
	- added `data-reason` and `data-dataset` attributes to make testing easier.

## Related Tickets & Documents

- Closes #618 

## QA Instructions, Screenshots, Recordings

Go to any LPA's page and compare with design in #618, e.g. [here](https://submit-pr-645.herokuapp.com/organisations/local-authority:LBH)

image

## Added/updated tests?

- [x] Yes

## Summary by CodeRabbit

- **New Features**
  - Introduced a new middleware function to fetch and process provisions data.
  - Added a new schema for `DatasetItem`, enhancing dataset representation.
  - Implemented a new macro for rendering dataset items, improving code organisation.

- **Bug Fixes**
  - Updated tests to reflect changes in dataset structure, ensuring accuracy in rendering.

- **Tests**
  - Added new helper functions and test cases for improved validation of dataset groups.

### CODE REVIEW

**Comment by CharliePatterson** [comment]
@rosado is this ready for design and product QA, or is it still going through code review?

**Comment by CharliePatterson** [comment]
I've checked the dashboards for a number of organisations who are part of various cohorts in ODP and those who aren't, and it all looks good to me.

@alextea any notes?

**Comment by DilwoarH** [comment]
I'm getting errors on many LPAs, eg: https://submit-pr-645.herokuapp.com/organisations/local-authority:AMB

**Comment by rosado** [comment]
The recent config change and endpoints' 'last updated' changes broke this PR, will fix soon.

**Review by GeorgeGoodall-GovUk — APPROVED** [review]

**Pull request merged**
