### PR TITLE
572 move guidance pages into submit service

### LINKED ISSUE #572: Move guidance pages into submit service
## Context:

- In the current iteration of the service the guidance lives outside of it, creating a disjointed and confusing journey for users (as evidenced through user research sessions).
- #573 will create a new navigation that enables users to more easily get to guidance pages from anywhere within the service, however, those pages would still exist outside of it, and thus be the UX equivalent of a culdesac.
- The scope of this ticket is to create a copy of the pages at https://www.planning.data.gov.uk/guidance/ and bring them into the submit repo, so that they exist within the service, including with the new navigation as per #573 

## Implementation details

- The current guidance sits in markdown files here: https://github.com/digital-land/digital-land.info/tree/main/application/templates/pages/guidance
- We want to keep the markdown files to ensure easy method of updating for content designers
- Create a guidance layout template to mirror what we currently have

### PR DESCRIPTION
**Pull request by DilwoarH**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Move guidance from main website to this repo

## Related Tickets & Documents

- Ticket Link
- Related Issue #
- Closes #572 #573

## QA Instructions, Screenshots, Recordings

Nov-06-2024 12-01-27 pm

## Added/updated tests?
_We encourage you to keep the code coverage percentage at 80% and above._

- [ ] Yes
- [ ] No, and this is why: _please replace this line with details on why tests
      have not been included_
- [ ] I need help with writing tests

## Release Notes

- **New Features**
	- Introduced a new guidance navigation section providing structured guidance for data providers.
	- Added a sub-navigation component for improved navigation within the application.
	- Launched several new guidance documents for local planning authorities on data preparation and compliance, including instructions on publishing data and maintaining data currency.
	- Implemented a new service for checking data compliance against technical specifications.

- **Bug Fixes**
	- Updated hyperlinks in various templates to point to relative URLs for better navigation.

- **Documentation**
	- Added multiple Markdown files detailing specifications for various datasets, including article 4 directions, conservation areas, listed buildings, and tree preservation orders.
	- Introduced a new layout template for guidance-related pages to enhance user experience.

### CODE REVIEW

**Review by rosado — APPROVED** [review]
Looks OK, some of the automated may be worth looking into (e.g. [this one](https://github.com/digital-land/submit/pull/613#discussion_r1827591175)). Also, can you update the `ConfigSchema` in `config/util.js` with the `guidanceNavigation` section?

**Comment by CharliePatterson** [comment]
One small thing on this page: https://submit-pr-613.herokuapp.com/guidance/try-check-publish-service

The link to the check tool seems to redirect to the landing page:

> [Try the Check planning and housing data service](https://submit-pr-613.herokuapp.com/).

**Comment by DilwoarH** [comment]
> One small thing on this page: https://submit-pr-613.herokuapp.com/guidance/try-check-publish-service
> 
> The link to the check tool seems to redirect to the landing page:
> 
> > [Try the Check planning and housing data service](https://submit-pr-613.herokuapp.com/).

done

**Review by GeorgeGoodall-GovUk — APPROVED** [review]
Code looks good! 
has Alex had a chance to review? if so id say all good to merge

**Review by GeorgeGoodall — APPROVED** [review]

**Review by GeorgeGoodall-GovUk — APPROVED** [review]

**Pull request merged**
